### ISSUE TITLE
I have error "Illegal Instruction" aarch64

### ISSUE THREAD

**Issue by ChaoLine892** [Qubic-Solutions/rqiner-builds#4]
When I start application on snapdragon 625, I have error "Illegal Instruction", but on snapdragon 7 gen 2 plus worked without problems

**Comment by Mineco1006** [comment]
Hey, the aarch64 version compiles for the neoverse-n1 architecture. If you want I can compile it for your other CPU as well

**Comment by ChaoLine892** [comment]
If possible, it wouldn't be bad

**Comment by ChaoLine892** [comment]
Thanks, it works!!!
