### ISSUE TITLE
I would like to request a current package for the aarch64 platform

### ISSUE THREAD

**Issue by 3r1c** [Qubic-Solutions/rqiner-builds#49]
I would like to request a current package for the aarch64 platform, as the currently available version is outdated and cannot be used. I receive the following message:

[2024-10-10T10:43:04Z INFO  rqiner] Rust > C++ ;)
[2024-10-10T10:43:04Z INFO  rqiner] rqiner v1.0.6
[2024-10-10T10:43:04Z ERROR rqiner_manager] Your miner is outdated! Please update to version >=1.0.12
thread 'main' panicked at /mnt/a/programming/qubic/rqiner/rqiner-manager/src/lib.rs:123:17:
Failed to connect to pool

**Comment by Condor62** [comment]
Maintenance for Qubic.Solutions since yesterday 2 pm. 
You hav to wait.

**Comment by 3r1c** [comment]
Thank you for your answer
