### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by za515217964** [Qubic-Solutions/rqiner-builds#6]
localhost% ls
rqiner-aarch64  rqiner-aarch64.1  sd
localhost% ./rqiner-aarch64.1 -t 8 -i PVCYBZWCPQPMREEGLACOBPWZTODDYMGLKFGJRKHNPGMXIPULSHBNXJIFTVND
[2024-03-08T18:03:05Z INFO  rqiner] Rust > C++ ;)
[2024-03-08T18:03:05Z INFO  rqiner] rqiner v0.3.6
[2024-03-08T18:03:05Z INFO  rqiner] Running Pool Miner
Error: InternalError

**Comment by Mineco1006** [comment]
This error can only happen on startup, have you tried running it again?

**Comment by za515217964** [comment]
yes, had try again, i  used it  on phone
