### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by catursawah** [Qubic-Solutions/rqiner-builds#7]
[2024-03-08T18:32:09Z INFO  rqiner] Rust > C++ ;)
[2024-03-08T18:32:09Z INFO  rqiner] rqiner v0.3.2
[2024-03-08T18:32:09Z INFO  rqiner] Running Pool Miner
Error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("pool.qubic.solutions")), port: None, path: "/connect", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: No address associated with hostname" }))

**Comment by xiaolin0199** [comment]
Change to a faster DNS
